server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location /api/count/ { proxy_pass http://proxy:8000/; }
    location /api/text/ { proxy_pass http://text-store:4000/; }
    location /api/monitor/ { proxy_pass http://monitor:7000/; }
    location / { try_files $uri $uri/ =404; }
}
